### ISSUE TITLE
[Feature Request] Option (or parameter?) to reverse the order of output.

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/ddu-filter-sorter_alpha#1]
I know ddu-ui-ff has a reversed option, but it starts the cursor at the bottom of the window, which is not what I want, so I'm requesting the feature on the source side.

**Comment by Shougo** [comment]
Please use `sorter_reversed`.

https://github.com/Shougo/ddu-filter-sorter_reversed

**Comment by lambdalisue** [comment]
Perfect 🎉
